### ISSUE TITLE
How to run the code?

### ISSUE THREAD

**Issue by shomedas** [kevinwortman/3d-convex-hulls#1]
I am noob to opencl. I  compiled the code using:

g++ -std=c++0x -o convex_hull convexHull3d.cpp -lOpenCL. It produced convex_hull binary. 

How do i run the convex_hull code.

I ran makepoints.py to get files of the form: 3_clusters.1024.in, cube_surface.1024.in, normal_origin.1024.in, uniform_cube.1024.in.

Does the convex hull calculation in the gpu or the cpu?

**Comment by kevinwortman** [comment]
The convex hull calculations happens on the GPU.

For context, this is an experimental implementation of the algorithm described in the academic research paper at
http://2012.cccg.ca/papers/paper17.pdf

This is not maintained software, and is probably not a good starting point for learning about OpenCL. Instead, I'd recommend working from one of the numerous books or online resources about OpenCL.
